name: Create branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        default: 'new_branch'
        required: false
        type: string
      sha:
        type: string
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.branch }}
          sha: ${{ inputs.sha }}
